version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist/live-poll-client/:/usr/share/nginx/html/
    depends_on:
      - live-poll
    ports:
      - 80:80
  live-poll:
    build:
      context: .
      dockerfile: ./akrons/Dockerfile
      args: 
        SERVICE: 'live-poll-api'
    volumes: 
      - ./live-poll.config.json:/usr/src/app/live-poll.config.json
    environment:
      - AKRONS_CONFIG=/usr/src/app/live-poll.config.json
    # ports:
    #   - 80:80
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports: 
      - 6379:6379